export { SlideLayout } from './SlideLayout';
export { SlideRenderer } from './SlideRenderer';
export { DeckProvider, useDeck } from './DeckProvider';
export { useNavigation } from './useNavigation';

// Templates
export {
  TitleHero,
  Agenda,
  SectionDivider,
  TwoColumnArgument,
  QuoteInsight,
  StatGridSlide,
  ImageCaption,
  ComparisonTableSlide,
  TimelineSlide,
  Roadmap,
  RecommendationAsk,
  Appendix,
  IconFeatures,
  DataDashboard,
  ProcessOverview,
  FunnelBreakdown,
  CycleExplainer,
  FlywheelSlide,
  SWOTAnalysis,
  ProsConsSlide,
  BeforeAfterSlide,
  VersusMatchup,
  TeamIntro,
  TestimonialSpotlight,
  PricingOverview,
  ScreenshotDemo,
  ImageStory,
  DataComparison,
  NumbersImpact,
  QuadrantAnalysis,
  OrgStructure,
  FlowDecision,
  GapBridge,
  RadarComparison,
  HeatmapView,
  ScoreCardSlide,
  NextStepsAction,
  ContactEnd,
  ChapterOpener,
  LogoShowcase,
} from './templates';
